[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib', 'node_modules']
fs_permissions = [{ access = "read-write", path = "./"}]


[rpc_endpoints]
# Default to Monad Testnet
default_network = "https://testnet-rpc.monad.xyz"

# Monad Networks
monadTestnet = "https://testnet-rpc.monad.xyz"

# Local development (optional)
localhost = "http://127.0.0.1:8545"

[etherscan]
# Monad doesn't use Etherscan verification yet
# Add Monad explorer config when available



[fmt]
line_length = 120
tab_width = 4
quote_style = "double"
bracket_spacing = true
int_types = "long"




# See more config options https://book.getfoundry.sh/reference/config/overview