/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  10143: {
    TwitterRaffle: {
      address: "0x967d74052FBae8F4117cAd958AaaCb5479f7e816",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_feeRecipient",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "RAFFLE_FEE",
          inputs: [],
          outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "createTwitterRaffle",
          inputs: [
            { name: "_tweetUrl", type: "string", internalType: "string" },
            { name: "_raffleType", type: "uint8", internalType: "enum TwitterRaffle.RaffleType" },
            { name: "_winnerCount", type: "uint256", internalType: "uint256" },
            { name: "_backupCount", type: "uint256", internalType: "uint256" }
          ],
          outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "getRaffle",
          inputs: [{ name: "raffleId", type: "uint256", internalType: "uint256" }],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct TwitterRaffle.Raffle",
              components: [
                { name: "id", type: "uint256", internalType: "uint256" },
                { name: "tweetUrl", type: "string", internalType: "string" },
                { name: "raffleType", type: "uint8", internalType: "enum TwitterRaffle.RaffleType" },
                { name: "winnerCount", type: "uint256", internalType: "uint256" },
                { name: "backupCount", type: "uint256", internalType: "uint256" },
                { name: "creator", type: "address", internalType: "address" },
                { name: "createdAt", type: "uint256", internalType: "uint256" },
                { name: "status", type: "uint8", internalType: "enum TwitterRaffle.RaffleStatus" },
                { name: "participants", type: "address[]", internalType: "address[]" },
                { name: "winners", type: "address[]", internalType: "address[]" },
                { name: "backups", type: "address[]", internalType: "address[]" },
                { name: "vrfRequestId", type: "uint256", internalType: "uint256" }
              ]
            }
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRaffleParticipants",
          inputs: [{ name: "raffleId", type: "uint256", internalType: "uint256" }],
          outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRaffleWinners",
          inputs: [{ name: "raffleId", type: "uint256", internalType: "uint256" }],
          outputs: [
            { name: "winners", type: "address[]", internalType: "address[]" },
            { name: "backups", type: "address[]", internalType: "address[]" }
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRecentRaffles",
          inputs: [{ name: "limit", type: "uint256", internalType: "uint256" }],
          outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRaffleTypeString",
          inputs: [{ name: "_type", type: "uint8", internalType: "enum TwitterRaffle.RaffleType" }],
          outputs: [{ name: "", type: "string", internalType: "string" }],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "getUserRaffles",
          inputs: [{ name: "user", type: "address", internalType: "address" }],
          outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getTotalRaffles",
          inputs: [],
          outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isTweetProcessed",
          inputs: [{ name: "tweetUrl", type: "string", internalType: "string" }],
          outputs: [{ name: "", type: "bool", internalType: "bool" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setParticipants",
          inputs: [
            { name: "raffleId", type: "uint256", internalType: "uint256" },
            { name: "_participants", type: "address[]", internalType: "address[]" }
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "TwitterRaffleCreated",
          inputs: [
            { name: "raffleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "creator", type: "address", indexed: true, internalType: "address" },
            { name: "tweetUrl", type: "string", indexed: false, internalType: "string" },
            { name: "raffleType", type: "uint8", indexed: false, internalType: "enum TwitterRaffle.RaffleType" },
            { name: "winnerCount", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "backupCount", type: "uint256", indexed: false, internalType: "uint256" }
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RaffleProcessing",
          inputs: [
            { name: "raffleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "timestamp", type: "uint256", indexed: false, internalType: "uint256" }
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "WinnersSelected",
          inputs: [
            { name: "raffleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "winners", type: "address[]", indexed: false, internalType: "address[]" },
            { name: "backups", type: "address[]", indexed: false, internalType: "address[]" }
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RaffleCancelled",
          inputs: [
            { name: "raffleId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "reason", type: "string", indexed: false, internalType: "string" }
          ],
          anonymous: false,
        }
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
